import type { FunilConfig } from './types';

/**
 * Mapa mental de LIGAÇÃO ATIVA (Nox Imóveis).
 * Premissa: o cliente ATENDEU. O objetivo da ligação é conduzir a conversa
 * e marcar a VISITA/reunião. Sem follow-up de mensagem.
 * Semente/fallback — o admin pode editar tudo depois.
 */
export const FUNIL_DEFAULT: FunilConfig = {
  produtos: [
    { key: 'orla_da_barra', label: 'Orla da Barra' },
    { key: 'barra_view', label: 'Barra View' },
    { key: 'viverde', label: 'Viverde' },
    { key: 'nao_sei', label: 'Prospecção geral' },
  ],
  objetivos: [],
  startNode: 'abertura',
  nodes: [
    {
      id: 'abertura',
      eyebrow: 'Início da ligação',
      titulo: 'Abertura — o cliente atendeu',
      descricao: 'Os primeiros segundos decidem a ligação. Sorria (dá pra ouvir no telefone 😊), diga quem é, o porquê da ligação e peça permissão. Leve e confiante.',
      mensagem: 'Oi, [Nome], tudo bem? Aqui é [Seu nome], da Nox Imóveis. Vi que você demonstrou interesse em imóveis aqui no Litoral e te liguei rapidinho pra entender melhor o que você procura e já te ajudar a achar algo que faça sentido. Você tem uns minutinhos pra gente conversar agora?',
      pergunta: 'Como o cliente reagiu?',
      choices: [
        { label: 'Topou conversar', icon: '👍', desc: 'Seguir para a sondagem', target: 'sondagem' },
        { label: 'Está sem tempo agora', icon: '⏰', desc: 'Agendar um retorno', target: 'agendar_retorno' },
        { label: 'Não lembra / desconfiou', icon: '🤨', desc: 'Gerar confiança primeiro', target: 'contexto' },
      ],
    },
    {
      id: 'contexto',
      eyebrow: 'Confiança',
      titulo: 'Cliente não lembra ou desconfiou',
      descricao: 'Relembre de onde veio o contato com naturalidade e deixe claro que a ligação é pra ajudar, não pra empurrar. Confiança primeiro.',
      mensagem: 'Sem problema, [Nome]! Você demonstrou interesse no nosso anúncio do [Produto] aqui no Litoral, e por isso te liguei — pra entender o que você procura e não ficar te mandando informação à toa. Prometo ser rápido: consigo te fazer só umas perguntinhas?',
      pergunta: 'E agora?',
      choices: [
        { label: 'Agora topou', icon: '👍', target: 'sondagem' },
        { label: 'Segue sem tempo', icon: '⏰', target: 'agendar_retorno' },
      ],
    },
    {
      id: 'agendar_retorno',
      eyebrow: 'Retorno',
      titulo: 'Cliente sem tempo agora',
      descricao: 'Não insista. Marque um horário específico e ligue pontualmente — pontualidade passa profissionalismo.',
      mensagem: 'Tranquilo, [Nome]! Qual seria um melhor horário pra eu te ligar? Prometo ser rápido e objetivo, só pra te entender e já te adiantar o que faz sentido pra você.',
      infoNote: 'Anote o horário combinado e ligue na hora certa. Quando ele atender, é só recomeçar do início.',
    },
    {
      id: 'sondagem',
      eyebrow: 'Sondagem',
      titulo: 'Entenda o cliente antes de oferecer',
      descricao: 'Quem pergunta conduz. Faça perguntas abertas e ESCUTE — só ofereça depois de entender. Use as perguntas abaixo como guia (adapte, não leia robótico).',
      mensagem: '• O que te fez procurar um imóvel aqui no Litoral agora?\n• Seria mais pra morar, curtir no verão ou investir?\n• Você já conhece a região? Já chegou a visitar algum imóvel por aqui?\n• Tem um prazo em mente ou está começando a pesquisar?',
      pergunta: 'Qual perfil apareceu?',
      choices: [
        { label: 'Quer morar', icon: '🏡', target: 'perfil_moradia' },
        { label: 'Quer veraneio / praia', icon: '🏖️', target: 'perfil_veraneio' },
        { label: 'Quer investir', icon: '📈', target: 'perfil_investimento' },
        { label: 'Ainda está pesquisando', icon: '🤔', desc: 'Ajudar a clarear o objetivo', target: 'perfil_indeciso' },
      ],
    },
    {
      id: 'perfil_moradia',
      eyebrow: 'Perfil · Moradia',
      titulo: 'Cliente quer morar',
      descricao: 'Conecte com o momento de vida dele. Pra morar, o que pesa é localização, entrega, estrutura e o dia a dia.',
      mensagem: 'Que bom, [Nome]! A gente tem boas opções pra morar aqui na região, tanto prontas quanto na planta com condições facilitadas. Como é pra você morar, faz toda diferença ver de perto a localização, a planta e a estrutura — é rapidinho e você já sente se é a sua cara.',
      pergunta: 'O que ele prefere?',
      choices: [
        { label: 'Pronto pra morar', icon: '🔑', target: 'fechar_visita' },
        { label: 'Aceita na planta', icon: '📐', target: 'fechar_visita' },
      ],
    },
    {
      id: 'perfil_veraneio',
      eyebrow: 'Perfil · Veraneio',
      titulo: 'Cliente quer veraneio',
      descricao: 'Venda a experiência: praia, lazer, família. E, se fizer sentido, a renda de temporada como bônus.',
      mensagem: 'Perfeito, [Nome]! Temos opções com estrutura de lazer estilo resort e fácil acesso à praia — e, se você quiser, algumas ainda geram renda com locação por temporada quando não estiver usando. Vale muito ver de perto pra sentir o clima do lugar.',
      pergunta: 'Como é o uso?',
      choices: [
        { label: 'Só pra curtir', icon: '🌴', target: 'fechar_visita' },
        { label: 'Curtir + gerar renda', icon: '💰', target: 'fechar_visita' },
      ],
    },
    {
      id: 'perfil_investimento',
      eyebrow: 'Perfil · Investimento',
      titulo: 'Cliente quer investir',
      descricao: 'Fale a língua dele: números, valorização e rentabilidade. Uma conversa presencial mostra os dados melhor que qualquer mensagem.',
      mensagem: 'Ótimo, [Nome]! A gente trabalha com empreendimentos em regiões em crescimento, com bom potencial de valorização, e também opções voltadas pra renda com locação — algumas com gestoras que cuidam de tudo. Numa conversa rápida eu te mostro os números e você vê qual estratégia rende mais pra você.',
      pergunta: 'Qual o foco?',
      choices: [
        { label: 'Valorização (revenda)', icon: '📊', target: 'fechar_visita' },
        { label: 'Renda mensal (locação)', icon: '🏨', target: 'fechar_visita' },
      ],
    },
    {
      id: 'perfil_indeciso',
      eyebrow: 'Perfil · Indeciso',
      titulo: 'Cliente ainda está pesquisando',
      descricao: 'Não pressione. Ajude a clarear o objetivo com uma pergunta simples e direcione.',
      mensagem: 'Sem problema, [Nome]! Deixa eu te ajudar a pensar: hoje você imagina esse imóvel mais pra morar, pra curtir no verão com a família, ou como um investimento que rende? Assim eu já te mostro o caminho certo.',
      pergunta: 'Com a resposta, qual o perfil?',
      choices: [
        { label: 'Morar', icon: '🏡', target: 'perfil_moradia' },
        { label: 'Veraneio', icon: '🏖️', target: 'perfil_veraneio' },
        { label: 'Investir', icon: '📈', target: 'perfil_investimento' },
      ],
    },
    {
      id: 'fechar_visita',
      eyebrow: 'Fechamento',
      titulo: 'Convide para a visita',
      descricao: 'O objetivo da ligação é ESTE: tirar o cliente do telefone e levar pra uma visita/reunião. Não pergunte "se" ele quer — pergunte "quando". Ofereça duas opções de horário.',
      mensagem: '[Nome], acho que vale muito você conhecer de perto pra sentir se é o que procura. Eu consigo te atender [dia] ou [dia] — o que fica melhor pra você, de manhã ou à tarde?',
      pergunta: 'Como o cliente reagiu?',
      choices: [
        { label: 'Topou e marcou', icon: '✅', desc: 'Confirmar a visita', target: 'visita_confirmada' },
        { label: 'Levantou uma objeção', icon: '🤔', desc: 'Contornar e voltar a fechar', target: 'objecoes' },
        { label: 'Prefere WhatsApp', icon: '💬', target: 'obj_whats' },
        { label: 'Não quer agora', icon: '🌙', desc: 'Encerrar com leveza', target: 'encerrar_leve' },
      ],
    },
    {
      id: 'objecoes',
      eyebrow: 'Objeções',
      titulo: 'Contorne a objeção e volte a fechar',
      descricao: 'Objeção é sinal de interesse. Acolha, responda com segurança e conduza de volta pra visita — sempre com duas opções de horário.',
      pergunta: 'Qual objeção apareceu?',
      choices: [
        { label: '"Tô só pesquisando"', icon: '🔎', target: 'obj_pesquisando' },
        { label: '"Achei caro / fora do orçamento"', icon: '💸', target: 'obj_preco' },
        { label: '"Vou pensar / falar com alguém"', icon: '🤝', target: 'obj_pensar' },
        { label: '"Me manda por WhatsApp"', icon: '💬', target: 'obj_whats' },
        { label: '"Não conheço bem a região"', icon: '📍', target: 'obj_regiao' },
      ],
    },
    {
      id: 'obj_pesquisando',
      eyebrow: 'Objeção',
      titulo: '"Tô só pesquisando"',
      mensagem: 'Perfeito, [Nome], pesquisar é o certo mesmo! E é justamente por isso que vale conhecer de perto — foto e vídeo não passam a real do imóvel. Sem compromisso nenhum, você já sai sabendo comparar de verdade. Prefere [dia] ou [dia]?',
      choices: [{ label: 'Voltar a marcar a visita', icon: '↩️', target: 'fechar_visita' }],
    },
    {
      id: 'obj_preco',
      eyebrow: 'Objeção',
      titulo: '"Achei caro / fora do orçamento"',
      mensagem: 'Entendo, [Nome]. E é bem por isso que vale a conversa: a gente tem opções e condições diferentes, e muita coisa que parece fora do orçamento tem um fluxo de pagamento que cabe. Deixa eu te mostrar as possibilidades — você prefere [dia] ou [dia]?',
      choices: [{ label: 'Voltar a marcar a visita', icon: '↩️', target: 'fechar_visita' }],
    },
    {
      id: 'obj_pensar',
      eyebrow: 'Objeção',
      titulo: '"Vou pensar / falar com esposo(a)"',
      mensagem: 'Claro, [Nome], decisão de imóvel é a dois mesmo! Que tal já trazerem os dois na visita? Assim vocês veem juntos e decidem com tudo na mão, sem eu ficar te mandando informação solta. Fica melhor [dia] ou [dia]?',
      choices: [{ label: 'Voltar a marcar a visita', icon: '↩️', target: 'fechar_visita' }],
    },
    {
      id: 'obj_whats',
      eyebrow: 'Objeção',
      titulo: '"Me manda por WhatsApp"',
      descricao: 'Aceite mandar, mas não deixe a conversa morrer no WhatsApp: puxe pra visita e, se ele insistir, combine um retorno com dia e hora.',
      mensagem: 'Mando sim, [Nome]! Mas te adianto: por WhatsApp vai só um pedacinho — quem realmente decide é vendo de perto. Que tal a gente já deixar a visita marcada e eu te mando o material antes, pra você chegar já sabendo? Prefere [dia] ou [dia]?',
      infoNote: 'Se insistir só no WhatsApp: mande o material e combine um retorno com dia e hora. Nunca deixe em aberto.',
      choices: [{ label: 'Voltar a marcar a visita', icon: '↩️', target: 'fechar_visita' }],
    },
    {
      id: 'obj_regiao',
      eyebrow: 'Objeção',
      titulo: '"Não conheço bem a região"',
      mensagem: 'Então esse é o melhor motivo pra vir, [Nome]! Eu te mostro a região, os acessos, a estrutura em volta — é o tipo de coisa que só sentindo no lugar. E de quebra você já conhece o imóvel. Fica bom [dia] ou [dia]?',
      choices: [{ label: 'Voltar a marcar a visita', icon: '↩️', target: 'fechar_visita' }],
    },
    {
      id: 'visita_confirmada',
      eyebrow: 'Visita marcada 🎉',
      titulo: 'Confirme e prepare a visita',
      descricao: 'Fechou! Agora confirme os detalhes e deixe tudo pronto pra visita ser impecável.',
      mensagem: 'Combinado, [Nome]! Então fica marcado pra [dia] às [Horário]. Vou te mandar a localização e um resumo por WhatsApp pra facilitar. Qualquer imprevisto, é só me avisar. Até lá! 😊',
      checklist: [
        'Confirmar dia e horário com o cliente',
        'Mandar a localização do ponto de encontro',
        'Mandar um resumo/booking do imóvel antes',
        'Separar 2 ou 3 opções alinhadas ao perfil dele',
        'Confirmar 1 dia antes (lembrete rápido)',
      ],
    },
    {
      id: 'encerrar_leve',
      eyebrow: 'Encerramento',
      titulo: 'Cliente não quer agora',
      descricao: 'Encerre com leveza e mantenha a porta aberta. Um "não agora" vira "sim" lá na frente.',
      mensagem: 'Sem problemas, [Nome]! Fico à disposição. Se em algum momento você quiser dar uma olhada nas oportunidades aqui do Litoral, é só me chamar que eu te ajudo com o maior prazer. Um abraço!',
    },
  ],
};
