[build]
  command = "npm run build"
  # A pasta 'publish' é gerenciada automaticamente pelo plugin do Next.js

[build.processing]
  skip_processing = false

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "out" 